services:
  demoapp:
    image: demoapp:1.0
    container_name: app
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/actuator/health
      interval: 5s
      timeout: 5s
      retries: 1
      start_period: 10s

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus-settings.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      demoapp:
        condition: service_healthy
