# Container image to run the code
FROM alpine:3.10

# Copy the code file to the container root
COPY entrypoint.sh /entrypoint.sh

# execute code file when container starts
ENTRYPOINT ["./entrypoint.sh"]
