name: Call Reusable 03
on:
  push:
    branches:
      - feature**
      - feat**

jobs:
  call-workflow-in-local-repo-job:
    uses: rafaelclaumann/random-study/.github/workflows/reusable-workflow-03.yaml@main
  
  accessing-workflow-ouputs-job:
    runs-on: ubuntu-latest
    needs: call-workflow-in-local-repo-job
    steps:
      - name: print-workflow-outputs
        run: |
          echo "Hello World"   
