name: Check Open PRS 2.0 Evoluido

on:
  push:
    branches:
      - teste/**

jobs:
  comment:
   runs-on: ubuntu-latest
   steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      
    - name: create PR request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr create -B main -H "github-workflows" --title 'Merge github-workflows into main' --body 'Created by Github action'
      
    - name: create PR request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          prs=$(
                gh pr list \
                  --repo $GITHUB_REPOSITORY \
                  --json baseRefName,headRefName \
                  --jq 'map(select(.baseRefName == "main" and .headRefName == "$GITHUB_REF_NAME")) | length'
              )

          if ((prs > 0)); then
              echo "ja existe um PR aberto de $GITHUB_REF_NAME -> main"
              exit 0
          fi

          readonly MAIN=$(gh api repos/$GITHUB_REPOSITORY/branches/main | jq -r .commit.sha)
          readonly FEATURE=$(gh api repos/$GITHUB_REPOSITORY/branches/$GITHUB_REF_NAME | jq -r .commit.sha)
          
          echo "main sha1: $MAIN"
          echo "$GITHUB_REF_NAME sha1: $FEATURE"
          
          if [[ $MAIN != $FEATURE ]]; then
            gh pr create \
              --base main \
              --head $GITHUB_REPOSITORY \
              --title "Merge $GITHUB_REF_NAME into main" \
              --assignee $GITHUB_REPOSITORY_OWNER \
              --body "Created by Github action"
          fi
          
          echo $(gh pr view)
