name: Github API Calls

on:
  - workflow_dispatch

jobs:
  comment:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/github-script@v6
      id: my-script
      with:
        result-encoding: string
        retries: 3
        script: |          
            const { data: pullRequest } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
          
            console.log(pullRequest.owner)
            return pullRequest
          
    - name: Get result
      run: echo "${{steps.my-script.outputs.result}}"          
