name: Check Open PRS 2.0 Evoluido

on:
  push:
    branches:
      - teste/**

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Create PR request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh pr list \
              --repo "rafaelclaumann/random-study" \
              --json baseRefName, headRefName \
              --jq 'map(select(.baseRefName == "main" and .headRefName == "teste/321")) | length'              
            
            echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
            echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
            
            gh pr list \
              --repo $GITHUB_REPOSITORY \
              --json baseRefName, headRefName \
              --jq 'map(select(.baseRefName == "main" and .headRefName == "$GITHUB_REF_NAME")) | length'
            
            prs=$(
                  gh pr list \
                    --repo $GITHUB_REPOSITORY \
                    --json baseRefName,headRefName \
                    --jq 'map(select(.baseRefName == "main" and .headRefName == "$GITHUB_REF_NAME")) | length'
                )

            echo "prs: $prs"
            if ((prs > 0)); then
                echo "ja existe um PR aberto de $GITHUB_REF_NAME -> main"
                exit 0
            fi

            readonly MAIN=$(gh api repos/$GITHUB_REPOSITORY/branches/main | jq -r .commit.sha)
            readonly FEATURE=$(gh api repos/$GITHUB_REPOSITORY/branches/$GITHUB_REF_NAME | jq -r .commit.sha)

            echo "main sha1: $MAIN"
            echo "$GITHUB_REF_NAME sha1: $FEATURE"

            if [[ $MAIN != $FEATURE ]]; then
              gh pr create \
                --base main \
                --head $GITHUB_REF_NAME \
                --title "Merge $GITHUB_REF_NAME into main" \
                --assignee $GITHUB_REPOSITORY_OWNER \
                --body "Created by Github action"
            fi

            echo $(gh pr view)
