name: "Create cluster using KinD"
on:
  - workflow_dispatch

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: Testing
        run: |
          kubectl apply -f deployment.yaml
          
          kubectl wait \
          --namespace=default \
          --for=condition=ready pod \
          --selector='app=coffee-shop' \
          --timeout=-1s
          
          kubectl run --rm -it nginx --image=nginx -- curl coffee-shop-svc:8080
        
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
