name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      some-secret:
        required: false

jobs:
  print_reusable_workflow_input_01:
    runs-on: ubuntu-latest
    steps:
      - name: echo_workflow_input
        run: |
          echo input(config-path): ${{ inputs.config-path }}
          echo
          echo secret(some-secret): ${{ secrets.some-secret }}
        shell: bash
