name: Reusable workflow - with outputs

on:
  workflow_call:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_label: "feature, automated pr"
          pr_title: "Pulling ${{ github.ref_name }} into main"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: build_hello_world
        run: |
          printf "$(java -version)\n"
          printf "$(mvn -version)\n"
          printf "\ncurrent_dir: $PWD\n"

          cd java/hello-world-v1/
          printf "current_dir: $PWD\n"
          printf "building java artifact!\n"

          mvn clean install \
          --threads 2C \
          --file pom.xml        
