name: Calling Reusable Workflow - Using Outputs

on:
  - workflow_dispatch

jobs:
  call-workflow-in-local-repo-job:
    uses: rafaelclaumann/random-study/.github/workflows/reusable-workflow-02.yaml@main
  
  accessing-workflow-ouputs-job:
    runs-on: ubuntu-latest
    needs: call-workflow-in-local-repo-job
    steps:
      - name: print-workflow-outputs
        run: |
          echo ${{ needs.call-workflow-in-local-repo-job.outputs.firstword }}
          echo ${{ needs.call-workflow-in-local-repo-job.outputs.secondword }}
