name: Calling Reusable Workflow

on:
  - workflow_dispatch

jobs:
  call-workflow-1-in-local-repo:
    uses: rafaelclaumann/random-study/.github/workflows/workflow-reusable-11.yaml@97944f5b437161a7d719676b72695887a60643fb
    with:
      config-path: CALL_REUSABLE_WORKFLOW_WITH_COMMIT_SHA

  call-workflow-2-in-local-repo:
    uses: rafaelclaumann/random-study/.github/workflows/workflow-reusable-11.yaml@main
    with:
      config-path: CALL_REUSABLE_WORKFLOW_WITH_BRANCH_NAME      
