name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: echo_workflow_input
        run: |
          echo input: ${{ inputs.config-path }}
        shell: bash            
