name: Calling Reusable Workflow

on:
  - workflow_dispatch

jobs:
  call-workflow-1-in-local-repo:
    uses: rafaelclaumann/random-study/.github/workflows/workflow-reusable-11.yaml@83267bd96b416906516685686e6285cede19d7e0
    with:
      config-path: CALL_REUSABLE_WORKFLOW_WITH_COMMIT_SHA

  call-workflow-2-in-local-repo:
    uses: rafaelclaumann/random-study/.github/workflows/workflow-reusable-11.yaml@main
    with:
      config-path: CALL_REUSABLE_WORKFLOW_WITH_BRANCH_NAME      
