name: JobOnRunnerAndServiceContainer

on:
  push:
    paths: 
      - ".github/workflows/workflow-07.yaml"

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      redis_service:
        image: redis
        ports:
          - 6739:6739
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: github-workflows

      - name: Install dependencies
        run: |
          cd git-workflows-study/
          echo $PWD
          ls -l

          npm version 
          npm init -y > /dev/null
          npm install redis

          
          echo "$(docker container ls -q | head -n 1)"
          docker logs $(docker container ls -q | head -n 1)

      - name: Connect to Redis
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6739      
        run: |
          cd git-workflows-study/        
          echo $PWD
          ls -l

          node redisclient.js
