name: Calling Reusable Workflow

on:
  - workflow_dispatch

jobs:
  call-workflow-1-in-local-repo:
    uses: rafaelclaumann/random-study/.github/workflows/reusable-workflow-01.yaml@bf435e6b90eff2525554c4b555bdb2cb6f7588cc
    with:
      config-path: CALL_REUSABLE_WORKFLOW_WITH_COMMIT_SHA

  call-workflow-2-in-local-repo:
    uses: rafaelclaumann/random-study/.github/workflows/reusable-workflow-01.yaml@main
    with:
      config-path: CALL_REUSABLE_WORKFLOW_WITH_BRANCH_NAME

  call-workflow-3-in-local-repo:
    uses: ./.github/workflows/reusable-workflow-01.yaml
    with:
      config-path: CALL_REUSABLE_WORKFLOW_LOCAL_REFERENCE

  call-workflow-4-in-local-repo-matrix-strategy:
    strategy:
      matrix:
        variables: [dev, stage, prod]
    uses: ./.github/workflows/reusable-workflow-01.yaml
    with:
      config-path: ${{ matrix.variables }}

  call-workflow-5-in-local-repo:
    uses: rafaelclaumann/random-study/.github/workflows/reusable-workflow-01.yaml@main
    with:
      config-path: CALL_REUSABLE_WORKFLOW_WITH_SECRET
    secrets:
      some-secret: ${{ secrets.MY_SECRET_SUPER_SECRET }}  
