name: using-variables-workflow

emv:
  USER_NAME="rafael"
  USER_PASSWORD="1234"

on:
  push:
    paths: 
      - ".github/workflows/workflow-02.yaml"

jobs:
  VariableUsageJob:
  runs-on: ubuntu-latest
  steps:
  - name: Using Workflow Variables
    run: |
      printf "{ $USER_NAME } and { $USER_PASSWORD }\n"
