name: RunningContainerJob

on:
  push:
    paths: 
      - ".github/workflows/workflow-05.yaml"

jobs:  
  job_on_container:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      env: 
        actor: ${{ github.actor }}

    steps:
      - name: checkot_main_branch
        uses: actions/checkout@main
        with:
          ref: main

      - name: describe_os_version
        run: |
          cat /etc/os-release

      - name: print_some_context_vars
        run: |
          echo "$actor"                 # actor from job env var
          echo "${{ github.actor }}"    # actor from github context https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

      - name: check_condition
        if: ${{ env.actor == 'RafaelClaumann' }}
        run: echo "OK!"
