name: Calling Reusable Workflow

on:
  - workflow_dispatch

jobs:
  call-workflow-2-in-local-repo:
    uses: rafaelclaumann/random-study/.github/workflows/workflow-reusable-11.yaml@main
    with:
      config-path: TESTE-CONFIG-PATH-INPUT
