name: sharing-artifacts

on:
  push:
    paths: 
      - ".github/workflows/workflow-04.yaml"

jobs:

  Android:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_main_branch
        uses: actions/checkout@v3
        with:
          ref: main
        run: |
          ls -l

      - name: Android
        run: |
          printf "\n$PWD\n"
          ls -l

          cd java
          printf "\n$PWD\n"          
          ls -l
        
          cd hello-world-v1
          printf "\n$PWD\n"
          ls -l
