name: using-variables-workflow

env:
  USER_NAME: "rafael"
  USER_PASSWORD: "1234"

on:
  push:
    paths: 
      - ".github/workflows/workflow-02.yaml"

jobs:
  variables_in_workflow_level:
    runs-on: ubuntu-latest
    steps:
      - name: using_variables
        run: printf "{ $USER_NAME } and { $USER_PASSWORD }\n"

  variables_in_job_level:
    runs-on: ubuntu-latest
    env:
      USER_NAME: "claumann"
      USER_PASSWORD: "4321"
    steps:
      - name: using_variables
        run: |
          printf "env vars created on jobs with same name as workflow env vars will
          override workflow env vars values.\n"
          printf "{ $USER_NAME } and { $USER_PASSWORD }\n" # claumann and 4321
