name: using-variables-workflow

env:
  USER_NAME: "rafael"
  USER_PASSWORD: "1234"

on:
  push:
    paths: 
      - ".github/workflows/workflow-02.yaml"

jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: using_workflow_level_variables
        run: printf "{ $USER_NAME } and { $USER_PASSWORD }\n"
