name: JobOnRunnerAndServiceContainer

on:
  push:
    paths: 
      - ".github/workflows/workflow-07.yaml"

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      redis_service:
        image: redis
        ports:
          - 5500:6739  #HOST_MACHINE_PORT:CONTAINER_PORT
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: github-workflows

      - name: Install dependencies
        run: |
          echo $PWD
          ls -l

          cd git-workflows-study/
          echo $PWD
          ls -l

          npm version 
          npm init -y > /dev/null
          npm install redis > /dev/null

      - name: Connect to Redis
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 5500      
        run: |
          echo $PWD
          ls -l
          echo "REDIS_HOST: $REDIS_HOST"
          echo "REDIS_PORT: $REDIS_PORT"   

          curl localhost:5500 -v
