name: using-variables-workflow

env:
  USER_NAME: "rafael"
  USER_PASSWORD: "1234"
  USER_ID: "abc-def"

on:
  push:
    paths: 
      - ".github/workflows/workflow-02.yaml"

jobs:
  github_env_file_content:
    runs-on: ubuntu-latest
    steps:
      - name: listing_variables
        run: cat $GITHUB_ENV
        
  variables_in_workflow_scope:
    runs-on: ubuntu-latest
    steps:
      - name: using_variables
        run: printf "{ $USER_NAME }, { $USER_PASSWORD } and { $USER_ID }\n"

  variables_in_job_scope:
    runs-on: ubuntu-latest
    env:
      USER_NAME: "claumann"
      USER_PASSWORD: "4321"
    steps:
      - name: using_variables
        run: |
          printf "job env vars overrides workflow env vars values\n"
          printf "{ $USER_NAME }, { $USER_PASSWORD } and { $USER_ID }\n" # claumann, 4321 and abc-def
          
  variables_in_step_scope:
    runs-on: ubuntu-latest
    steps:
      - name: using_variables
        env:
          USER_NAME: "bernardes"
          USER_PASSWORD: "98765"
        run: |
          printf "step env vars overrides workflow env vars values\n"
          printf "{ $USER_NAME }, { $USER_PASSWORD } and { $USER_ID }\n" # bernardes, 98765 and abc-def
